### ISSUE TITLE
Throttling and plus validation

### ISSUE THREAD

**Issue by pietvanzoen** [plusfries/plusfries#12]
continued from here: https://github.com/pietvanzoen/discussie/issues/12

cc @keepitterron

**Comment by pietvanzoen** [comment]
Seems like the kudos feature gives a cookie back on the kudos count GET request. It uses that as a "user" token, and I guess stores that when you give kudos, because you can only give kudos once.

I agree. Medium's thing doesn't seem too valuable. One plus for one person seems better to me. If you really want you can clear cookies and do it again. But i'm not too worried about that.

I think we can also use the cookie to validate (to a certain degree) that the plus is coming from the correct domain.

**Comment by keepitterron** [comment]
Agreed. Let's go for the cookie and see how far it takes us and if there's any downsides to it

**Comment by pietvanzoen** [comment]
Sounds good. 

Looks like kudos also uses localStorage to track what’s already been liked. Might be another good way to prevent lazy spamming.

**Comment by pietvanzoen** [comment]
Looked at it again and they don't use the cookie to validate. You can curl it without a cookie. ¯\\__(ツ)_/¯ So i guess the only safety there is throttling and the UI only allowing one "kudos" without clearing your LocalStorage.

**Comment by pietvanzoen** [comment]
I'm pretty ok with these two covering this issue:
- https://github.com/plusfries/plusfries/commit/71ccd810c4fb4d7d749812945a968d9b64b16c31
- https://github.com/plusfries/plusfries/commit/563a361a8a6dd23453490ec0e269a19cfeff5993#diff-52503f2920dcbf5082edfc5670ede0f1
